<a href="https://colab.research.google.com/github/lostysky/Data-Engineering-codeboosters-internship-2026/blob/main/Day_05_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
a = pd.read_csv("data.csv")

In [ ]:
a.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [ ]:
a.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [ ]:
a.isnull().any()

date             False
price            False
bedrooms         False
bathrooms        False
sqft_living      False
sqft_lot         False
floors           False
waterfront       False
view             False
condition        False
sqft_above       False
sqft_basement    False
yr_built         False
yr_renovated     False
street           False
city             False
statezip         False
country          False
dtype: bool

In [ ]:
x=a[["sqft_living"]]
x

      sqft_living
0            1340
1            3650
2            1930
3            2000
4            1940
...           ...
4595         1510
4596         1460
4597         3010
4598         2090
4599         1490

[4600 rows x 1 columns]

In [ ]:
y=a[["price"]]
y

             price
0     3.130000e+05
1     2.384000e+06
2     3.420000e+05
3     4.200000e+05
4     5.500000e+05
...            ...
4595  3.081667e+05
4596  5.343333e+05
4597  4.169042e+05
4598  2.034000e+05
4599  2.206000e+05

[4600 rows x 1 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
print("X train")
x_train

X train

      sqft_living
4349         3260
3697         3530
1818         1030
112          1050
4016         1450
...           ...
3702         3660
3322          770
354          1840
3000          840
700          2510

[3680 rows x 1 columns]

In [ ]:
print("y train")
y_train

y train

         price
4349  188000.0
3697  963000.0
1818  718000.0
112   300000.0
4016  410000.0
...        ...
3702  530000.0
3322  275000.0
354   538000.0
3000  325000.0
700   955000.0

[3680 rows x 1 columns]

In [ ]:
print("X test")
x_test

X test

      sqft_living
1842         2060
1260         1230
2409         2050
1284         1670
2399         2130
...           ...
1075         1390
752          1700
1266         1080
2414         1769
2741         3600

[920 rows x 1 columns]

In [ ]:
print("Y test")
y_test

Y test

         price
1842  200000.0
1260  607000.0
2409  670000.0
1284  585000.0
2399  850000.0
...        ...
1075  270000.0
752   349950.0
1266  132500.0
2414  495000.0
2741  403500.0

[920 rows x 1 columns]